ctrl_interface=/run/wpa_supplicant
update_config=1
country=US
dik_cipher=0
dik=86617C10A716DC1FE1A5C4E3DEB37296

network={
	ssid="ATTVcr7kPm"
	scan_ssid=1
	bssid=d0:fc:d0:93:af:b4
	psk="t8fju?rbrhdj"
	proto=RSN
	key_mgmt=WPA-PSK
	pairwise=CCMP
	priority=10
}
