ctrl_interface=/run/wpa_supplicant
update_config=1
country=US
dik_cipher=0
dik=D7125A09E77BE60E035995974A45E005

network={
	ssid="seanwang_tp_5G_WPA3PSK"
	scan_ssid=1
	psk="12345678"
	sae_password="12345678"
	key_mgmt=SAE
	priority=60
	ieee80211w=2
}

network={
	ssid="seanwang_tp_2.4G_WPA3PSK"
	scan_ssid=1
	psk="12345678"
	sae_password="12345678"
	key_mgmt=SAE
	priority=55
	ieee80211w=2
}

network={
	ssid="seanwang_tp_5G_WPA2PSK"
	scan_ssid=1
	psk="12345678"
	key_mgmt=WPA-PSK
	priority=50
}

network={
	ssid="seanwang_tp_2.4G_WPA2PSK"
	scan_ssid=1
	psk="12345678"
	key_mgmt=WPA-PSK
	priority=45
}

network={
	ssid="seanwang_tp_5G_WPAPSK"
	scan_ssid=1
	psk="12345678"
	key_mgmt=WPA-PSK
	priority=40
}

network={
	ssid="seanwang_tp_2.4G_WPAPSK"
	scan_ssid=1
	psk="12345678"
	key_mgmt=WPA-PSK
	priority=35
}
