ctrl_interface=/run/wpa_supplicant
update_config=1
country=US
dik_cipher=0
dik=FE673385556480D0040EB4272D462D6E

network={
	ssid="ATTVcr7kPm"
	scan_ssid=1
	psk="t8fju?rbrhdj"
	proto=RSN
	key_mgmt=WPA-PSK
	pairwise=CCMP
	priority=10
	bssid=d0:fc:d0:93:af:b8
}

network={
	ssid="ATTVcr7kPm"
	scan_ssid=1
	psk="t8fju?rbrhdj"
	proto=RSN
	key_mgmt=WPA-PSK
	pairwise=CCMP
	priority=10
	bssid=d0:fc:d0:93:af:bc
}
