driver=nl80211
ssid=MTK-OPEN-5G
hw_mode=a
channel=36

logger_stdout=-1
logger_stdout_level=0

ieee80211n=1
ieee80211ac=1
wmm_enabled=1

auth_algs=1
ignore_broadcast_ssid=0

ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
