driver=nl80211
ssid=MTK-OPEN-5G-HE
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0

logger_stdout=-1
logger_stdout_level=0

country_code=US
hw_mode=a
channel=36

ieee80211d=1
ieee80211h=1

wmm_enabled=1
ieee80211n=1
ieee80211ac=1
ieee80211ax=1

ht_capab=[HT40+]

require_ht=1
require_vht=1

vht_oper_chwidth=1
vht_oper_centr_freq_seg0_idx=42

he_oper_chwidth=1
he_oper_centr_freq_seg0_idx=42

auth_algs=1
ignore_broadcast_ssid=0
