ctrl_interface=/run/wpa_supplicant
update_config=1
country=US
dik_cipher=0
dik=606AE16636112951430959DD74878533

network={
	ssid="MTK-WPA2-2G-HE"
	psk="12345678"
	proto=RSN
	key_mgmt=WPA-PSK
	pairwise=CCMP
	scan_freq=2437
	freq_list=2437
}
