ctrl_interface=/run/wpa_supplicant
update_config=1
country=US
dik_cipher=0
dik=37E1E03F4AC97E8A888E17B81D6F87D3

network={
	ssid="MTK-OWE-2G-HE"
	proto=RSN
	key_mgmt=OWE
	pairwise=CCMP
	scan_freq=2437
	freq_list=2437
	ieee80211w=2
}
