ctrl_interface=/run/wpa_supplicant
update_config=1
country=US
dik_cipher=0
dik=C65658C18300F4B9BBCDB3C2C4D3498F

network={
	ssid="MTK-OPEN-5G-HIDDEN"
	scan_ssid=1
	key_mgmt=NONE
	scan_freq=5180
	freq_list=5180
}
