ctrl_interface=/run/wpa_supplicant
update_config=1
country=US
sae_pwe=2
dik_cipher=0
dik=C2A03635F164AA8B11CF6E1C4CA2B083

network={
	ssid="MTK-WPA2WPA3-5G"
	psk="12345678"
	proto=RSN
	key_mgmt=WPA-PSK SAE
	pairwise=CCMP
	scan_freq=5180
	freq_list=5180
	ieee80211w=1
}
