ctrl_interface=/run/wpa_supplicant
update_config=1
country=US
dik_cipher=0
dik=1BA0B0DF1BE03BA3D2E8C2599EE71F13

network={
	ssid="MTK-WPA2-5G-HE"
	psk="12345678"
	proto=RSN
	key_mgmt=WPA-PSK
	pairwise=CCMP
	scan_freq=5180
	freq_list=5180
}
