ctrl_interface=/run/wpa_supplicant
update_config=1
country=US
dik_cipher=0
dik=726BABF22EFC301EC9A25126B4AEC831

network={
	ssid="MTK-OWE-5G-HE"
	proto=RSN
	key_mgmt=OWE
	pairwise=CCMP
	scan_freq=5180
	freq_list=5180
	ieee80211w=2
}
