ctrl_interface=/run/wpa_supplicant
update_config=1
country=US
dik_cipher=0
dik=1136FB5BE98A111FC7D3176A6F360B0E

network={
	ssid="MTK-WPA2-2G"
	psk="12345678"
	proto=RSN
	key_mgmt=WPA-PSK
	pairwise=CCMP
	scan_freq=2437
	freq_list=2437
}
