ctrl_interface=/run/wpa_supplicant
update_config=1
country=US
dik_cipher=0
dik=F4E2BBA4A1EEDE4C1DFD17A124A34DB9

network={
	ssid="MTK-WPA2-5G"
	psk="12345678"
	proto=RSN
	key_mgmt=WPA-PSK
	pairwise=CCMP
	scan_freq=5180
	freq_list=5180
}
