ctrl_interface=/run/wpa_supplicant
update_config=1
country=US
sae_pwe=2
dik_cipher=0
dik=9624EF82C0F5FB21F56A670A64ACF767

network={
	ssid="MTK-WPA3-5G"
	sae_password="12345678"
	proto=RSN
	key_mgmt=SAE
	pairwise=CCMP
	scan_freq=5180
	freq_list=5180
	ieee80211w=2
}
