ctrl_interface=/run/wpa_supplicant
update_config=1
country=US
sae_pwe=2
dik_cipher=0
dik=028D256F1188D6668A88B6288568AD5B

network={
	ssid="MTK-WPA2WPA3-5G-HE"
	psk="12345678"
	proto=RSN
	key_mgmt=WPA-PSK SAE
	pairwise=CCMP
	ieee80211w=1
}
