ctrl_interface=/run/wpa_supplicant
update_config=1
country=US
sae_pwe=2
dik_cipher=0
dik=64FA60E8F79B9837547A0C8F18D377D1

network={
	ssid="MTK-WPA3-2G-HE"
	sae_password="12345678"
	proto=RSN
	key_mgmt=SAE
	pairwise=CCMP
	scan_freq=2437
	freq_list=2437
	ieee80211w=2
}
