ctrl_interface=/run/wpa_supplicant
update_config=1
country=US
sae_pwe=2
dik_cipher=0
dik=BCB02956702009838FD177BFBA6271A2

network={
	ssid="MTK-WPA3-5G-HE"
	sae_password="12345678"
	proto=RSN
	key_mgmt=SAE
	pairwise=CCMP
	ieee80211w=2
}
